kind: Service
apiVersion: v1
metadata:
  name: service-sportmen
  annotations:
    cloud.google.com/backend-config: '{"default": "sportmen-config"}'
spec:
  type: NodePort
  selector:
    app: sportmen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31021